CREATE TABLE TBLUSER (
    ID           BIGSERIAL PRIMARY KEY,
    EMAIL        VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD     VARCHAR(255),
    NICKNAME     VARCHAR(100) NOT NULL,
    CELNO        VARCHAR(20),
    PROVIDER     VARCHAR(20) NOT NULL,
    PROVIDER_ID  VARCHAR(255),
    REG_DATE     TIMESTAMP NOT NULL DEFAULT now(),
    MOD_DATE     TIMESTAMP NOT NULL DEFAULT now(),
    DEL_YN       VARCHAR(1) NOT NULL DEFAULT 'N'
);

CREATE UNIQUE INDEX UX_TBLUSER_PROVIDER_ID ON TBLUSER (PROVIDER_ID) WHERE PROVIDER_ID IS NOT NULL;
