CREATE TABLE TBLMATCHGROUP (
    ID             BIGSERIAL PRIMARY KEY,
    TITLE          VARCHAR(200) NOT NULL,
    PASSWORD       VARCHAR(255),
    SHARE_TOKEN    VARCHAR(64) UNIQUE,
    TOTAL_PLAYERS  INT NOT NULL,
    COURT_COUNT    INT NOT NULL,
    GAME_COUNT     INT NOT NULL,
    REG_ID         BIGINT NOT NULL REFERENCES TBLUSER(ID),
    REG_DATE       TIMESTAMP NOT NULL DEFAULT now(),
    MOD_ID         BIGINT REFERENCES TBLUSER(ID),
    MOD_DATE       TIMESTAMP NOT NULL DEFAULT now(),
    DEL_YN         VARCHAR(1) NOT NULL DEFAULT 'N'
);

CREATE TABLE TBLMATCH (
    ID             BIGSERIAL PRIMARY KEY,
    MATCHGROUP_ID  BIGINT NOT NULL REFERENCES TBLMATCHGROUP(ID) ON DELETE CASCADE,
    COURT_NO       INT NOT NULL,
    ROUND_NO       INT NOT NULL,

    PLAYER1_NAME   VARCHAR(20) NOT NULL,
    PLAYER1_GRADE  VARCHAR(1) NOT NULL,
    PLAYER1_GENDER VARCHAR(1),
    PLAYER1_AGE    INT,

    PLAYER2_NAME   VARCHAR(20) NOT NULL,
    PLAYER2_GRADE  VARCHAR(1) NOT NULL,
    PLAYER2_GENDER VARCHAR(1),
    PLAYER2_AGE    INT,

    PLAYER3_NAME   VARCHAR(20) NOT NULL,
    PLAYER3_GRADE  VARCHAR(1) NOT NULL,
    PLAYER3_GENDER VARCHAR(1),
    PLAYER3_AGE    INT,

    PLAYER4_NAME   VARCHAR(20) NOT NULL,
    PLAYER4_GRADE  VARCHAR(1) NOT NULL,
    PLAYER4_GENDER VARCHAR(1),
    PLAYER4_AGE    INT,

    TEAM1_SCORE    INT,
    TEAM2_SCORE    INT,

    REG_ID         BIGINT NOT NULL REFERENCES TBLUSER(ID),
    REG_DATE       TIMESTAMP NOT NULL DEFAULT now(),
    MOD_ID         BIGINT REFERENCES TBLUSER(ID),
    MOD_DATE       TIMESTAMP NOT NULL DEFAULT now(),
    DEL_YN         VARCHAR(1) NOT NULL DEFAULT 'N'
);

CREATE INDEX IX_TBLMATCH_MATCHGROUP_ID ON TBLMATCH(MATCHGROUP_ID);
