ALTER TABLE TBLUSER ADD COLUMN IF NOT EXISTS NAME VARCHAR(100);

UPDATE TBLUSER
SET NAME = COALESCE(NULLIF(NICKNAME, ''), split_part(EMAIL, '@', 1), '사용자');

ALTER TABLE TBLUSER ALTER COLUMN NAME SET NOT NULL;
